@rootURL = http://localhost:5110

GET {{rootURL}}/weatherforecast/
Accept: application/json

###
GET {{rootURL}}/api/books
Accept: application/json

###
GET {{rootURL}}/api/books/2
Accept: application/json

###
POST {{rootURL}}/api/books
Content-Type: application/json
{
  "id":7,
  "title": "New Book",
  "author": "John Doe",
  "publishedDate": "2023-10-01T00:00:00Z"
}
###
PUT {{rootURL}}/api/books/7
Content-Type: application/json
{
  "id":7,
  "title": "New Book",
  "author": "Samin",
  "publishedDate": "2023-10-02T00:00:00Z"
}